pub const ATOMS_PER_ATHO: u64 = 100_000_000;
pub const MAX_SUPPLY_ATHO: u64 = 168_000_000;
pub const INITIAL_BLOCK_REWARD_ATHO: u64 = 50;
pub const GENESIS_COINBASE_ATOMS: u64 = INITIAL_BLOCK_REWARD_ATHO * ATOMS_PER_ATHO;
pub const HALVING_INTERVAL_BLOCKS: u64 = 1_680_000;
pub const MIN_TX_FEE_ATOMS: u64 = 500;
pub const BLOCK_TIME_SECONDS: u64 = 75;
pub const TARGET_BLOCK_TIME_SECONDS: u64 = BLOCK_TIME_SECONDS;
pub const POW_RETARGET_INTERVAL_BLOCKS: u64 = 1;
pub const POW_AVERAGING_WINDOW_BLOCKS: u64 = 17;
pub const POW_MEDIAN_WINDOW_BLOCKS: u64 = 11;
pub const POW_DAMPING_FACTOR: u64 = 4;
pub const POW_MAX_ADJUST_UP_PERCENT: u64 = 16;
pub const POW_MAX_ADJUST_DOWN_PERCENT: u64 = 32;
pub const SHA3_384_HASH_BITS: usize = 384;
pub const SHA3_384_HASH_HEX_CHARS: usize = 96;
pub const WITNESS_SCALE_FACTOR: usize = 4;
pub const MAX_BLOCK_SIZE_BYTES: usize = 2_000_000;
pub const MAX_BLOCK_WEIGHT: usize = MAX_BLOCK_SIZE_BYTES * WITNESS_SCALE_FACTOR;
pub const MAX_BLOCK_SERIALIZED_BYTES: usize = MAX_BLOCK_WEIGHT;
pub const MAX_TRANSACTION_SIZE_BYTES: usize = 250_000;
pub const ADDRESS_DIGEST_BYTES: usize = 32;
pub const ADDRESS_CHECKSUM_BYTES: usize = 4;
pub const ADDRESS_CHECKSUM_BASE56_CHARS: usize = 6;
pub const STANDARD_TRANSACTION_ALLOCATION: f64 = 0.95;

pub const ADDRESS_ROLE_DOMAIN: &str = "ATHO_ADDR_V1";

pub const BASE56_ALPHABET: &str =
    "23456789ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz";
